<!-- Responsible For the Header profile links -->
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSessionFactory = $objectManager->get('Magento\Customer\Model\SessionFactory');
$customerSession = $customerSessionFactory->create();
?>
<div class="userIcon topIcon">
<div class="customerAccountDropdown">
	
	<div class="titleICon">
		<svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512"><path d="M224 256A128 128 0 1 0 224 0a128 128 0 1 0 0 256zm-45.7 48C79.8 304 0 383.8 0 482.3C0 498.7 13.3 512 29.7 512H418.3c16.4 0 29.7-13.3 29.7-29.7C448 383.8 368.2 304 269.7 304H178.3z"/></svg>
	</div>
	<div class="customerAccounthiddenlink" style="display: none;">
		<ul class="listAccountLinks">

		<?php  if(!$customerSession->isLoggedIn()) {  ?>
			<li><a href="<?php  echo $this->getUrl('customer/account/create/'); ?>"><?= __('Register') ?></a></li>
			<li><a href="<?php  echo $this->getUrl('customer/account/login'); ?>"><?= __('Sign In') ?></a></li>
			
		<?php } else { ?>
			<li><a href="<?php  echo $this->getUrl('customer/account/'); ?>"><?= __('My Account') ?></a></li>
			<li><a href="<?php  echo $this->getUrl('sales/order/history/'); ?>"><?= __('Order History') ?></a></li>
			<li><a href="<?php  echo $this->getUrl(''); ?>"><?= __('Size Chart') ?></a></li>
			<li><a href="<?php  echo $this->getUrl('customer/account/logout'); ?>"><?= __('Logout') ?></a></li>

		<?php } ?>

		</ul>
	</div>
</div>
</div>
<script type="text/javascript">
    require(['jquery', 'jquery/ui'], function($){
        jQuery('.customerAccountDropdown').click(function(){
            jQuery('.customerAccounthiddenlink').toggle();
        });
      });
</script>